# inventory_prod.ini
[master]
master-prod ansible_host=51.44.53.141 ansible_user=ubuntu public_ip=51.44.53.141

[workers]
worker-prod-1 ansible_host=13.39.94.24
worker-prod-2 ansible_host=13.38.153.118

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/pixelwar
ansible_ssh_common_args='-o StrictHostKeyChecking=no'